# Generated by Django 3.2.6 on 2021-12-30 03:04

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211228_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
